-- AlterTable
ALTER TABLE "Activity" ALTER COLUMN "createdDatetime" SET DATA TYPE TIMESTAMPTZ,
ALTER COLUMN "updatedDatetime" SET DATA TYPE TIMESTAMPTZ;

-- AlterTable
ALTER TABLE "Mood" ALTER COLUMN "createdDatetime" SET DATA TYPE TIMESTAMPTZ,
ALTER COLUMN "updatedDatetime" SET DATA TYPE TIMESTAMPTZ;
