name: mimood-frontend
on:
  push:
    branches:
      - main
jobs:
  deploy-ui:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: setup node
        uses: actions/checkout@v4
        with:
          node-version: '18'

      - name: install dependencies
        working-directory: ./frontend
        run: npm install

      - name: build
        working-directory: ./frontend
        run: |
          npm run build
          ls dist

      - name: configure aws
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          role-duration-seconds: 900
          aws-region: us-east-1

      - name: upload built to s3
        env:
          S3_BUCKET: "s3://mimood"
          UI_PATH: "mimood-ui"
        working-directory: ./frontend/dist
        run: |
          aws s3 sync . ${S3_BUCKET}/${UI_PATH} --delete --cache-control max-age=0,no-cache,no-store,must-revalidate
